version: "3.8"

services:
  app:
    build: .
    ports:
      - "8000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV
      - DATABASE_URL
      - CLOUDINARY_CLOUD_NAME
      - CLOUDINARY_API_KEY
      - CLOUDINARY_API_SECRET
      - JWT_SECRET